message = [
    dst : uint,
    ?src : uint,
    ?msg_id : uint,
    msg_type : uint,
    ?msg : bytes
]
msg_type_enum = &(
    Pub0Req : 0,
    Pub1Req: 1,
    Pub2Req: 2,
    Alive: 3
    NameReq: 4,
    NameResp: 5,
    DescReq: 6,
    DescResp: 7,
    Pub1Resp: 8,
    Pub2Resp: 9,
    SetReq: 10,
    SetResp: 11,
    GetReq: 12,
    GetResp: 13,
    WillReq: 14,
    WillResp: 15,
)