ps4-controller-event = {
    buttons: {
        square: bool,
        triangle: bool,
        circle: bool,
        cross: bool,
        l1: bool,
        r1: bool,
        l2: uint,
        r2: uint,
        share: bool,
        options: bool,
        l3: bool,
        r3: bool,
        ps: bool,
        touchpad: bool
    },
    joystick: {
        left: {
            x: int,
            y: int
        },
        right: {
            x: int,
            y: int
        }
    }
}
ps4-controller-cmd = {
    rumble: {
        left: uint,
        right: uint
    },
    lightbar: {
        r: uint,
        g: uint,
        b: uint
    }
}