
message = Connect
	/ ConnAck
	/ Publish
	/ Subscribe
	/ Request
	/ Reply
	/ Log
	/ Disconnect
	/ Metrics

Level = INFO
	/ WARN
	/ ERROR
	/ DEBUG
	/ TRACE
	/ FATAL .size 1

Qos = 0
	/ 1
	/ 2 .size 1

Log = {
	timestamp: uint,
	message: text,
	? device: text,
	? level: Level,
	? file: text,
	? line: uint,
	? function: text,
}

Connect = { mtu: uint, alive: uint, ? fragmentation: bool, }

ConnAck = { mtu: uint, alive: uint, ? fragmentation: bool, }

Publish = {
	topic: text,
	payload: bytes,
	? qos: Qos,
	? retain: bool,
}

Subscribe = { topic: text, ? qos: Qos }

Request = { id: uint, ? method: text, ? params: text, }

Reply = { id: uint, ? result: text, ? error: text, }

Disconnect = { }

Metrics = { }
